### PR TITLE
Simplefy ext-GD configure

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by bendavies** [comment]
I think the previous version is easier to read and is self documenting. this just looks confusing and hard to work out why it does it this way.

**Comment by WyriHaximus** [comment]
@bendavies makes sense. Could add a comment why. Reason behind the reason for this change is that with PHP 7.4 this was required to check, but since two weeks this check is also required PHP 7.3 on Alpine 3.12 and only the NTS version, ZTS is fine. Spent way more time on it earlier this evening to make it work that I just gave up and went with this route :(

**Comment by bendavies** [comment]
Aha right. Definitely more complex than the original fix then. 
I guess a comment would suffice as you say!

**Comment by WyriHaximus** [comment]
Yeah, not a super fan of this either. But once #63 is in, and we're only building 7.4 and up this can be simplified to just one of them

**Pull request merged**
